package com.kriss.smsshield.model

data class RegisterRequest(val name:String,val username:String,val email:String,val password:String)
data class LoginRequest(val username:String,val password:String)
data class UserDto(val id:Int,val name:String,val username:String,val email:String,val role:String="user",val languagePreference:String,val notificationsEnabled:Boolean,val autoDeleteHistory:Boolean=false)
data class TokenResponse(val accessToken:String,val tokenType:String,val user:UserDto)
data class ForgotPasswordRequest(val email:String)
data class VerifyResetCodeRequest(val email:String,val token:String)
data class ResetPasswordRequest(val email:String,val token:String,val newPassword:String,val confirmPassword:String)
data class MessageResponse(val message:String)
data class GoogleAuthRequest(val idToken:String)
data class FacebookAuthRequest(val accessToken:String)
data class FirebaseSyncRequest(val idToken:String, val name:String? = null, val username:String? = null)
data class ClassificationRequest(val message:String,val senderNo:String?=null)
data class ClassificationResponse(val smsId:Int,val label:String,val statusCode:Int,val confidence:Double,val language:String,val scamType:String?,val explanation:String,val ruleOverride:Boolean,val classProbabilities:Map<String,Double>)
data class HistoryItem(val smsId:Int,val message:String,val language:String,val label:String,val confidence:Double,val scamType:String?,val explanation:String,val createdAt:String)
data class ReportRequest(val smsId:Int,val reason:String)
data class FeedbackRequest(val smsId:Int?=null,val feedbackText:String?=null,val expectedLabel:String?=null)
data class BatchRequest(val messages:List<ClassificationRequest>)
data class BatchHistoryItemDto(val smsId:Int,val message:String,val label:String,val confidence:Double,val language:String,val scamType:String?,val explanation:String)
data class BatchHistoryResponse(val id:Int,val batchId:String,val totalCount:Int,val safeCount:Int,val spamCount:Int,val scamCount:Int,val reportLanguage:String="en",val items:List<BatchHistoryItemDto>,val createdAt:String)
data class SettingsUpdate(val languagePreference:String?=null,val notificationsEnabled:Boolean?=null,val autoDeleteHistory:Boolean?=null)
data class HealthResponse(val status:String,val modelReady:Boolean,val modelVersion:String)
data class PublishSpamRequest(val smsId:Int,val senderNo:String,val message:String)
data class PublishedSpamItem(val id:Int,val senderNo:String,val message:String,val label:String,val publishedAt:String)
data class UserReportItem(val id:Int,val smsId:Int,val message:String,val reason:String,val reportDate:String)
data class UserFeedbackItem(val id:Int,val smsId:Int?,val message:String?,val feedbackText:String?,val expectedLabel:String?,val createdAt:String)
data class ProfileUpdate(val name:String,val username:String,val email:String)
data class PasswordChange(val currentPassword:String,val newPassword:String)
data class DeleteAccountRequest(val confirmation:String)
data class ActivityLogItem(val id:Int,val action:String,val detail:String?,val createdAt:String)
data class AdminMetrics(val users:Int,val messages:Int,val reports:Int,val classifications:Map<String,Int>)
data class AdminLatency(val average:Double,val p50:Double,val p95:Double,val p99:Double)
data class AdminClassificationPerformance(val requests:Int,val averageMs:Double,val within2SecondsPercent:Double)
data class AdminPerformance(val windowHours:Int,val requests:Int,val serverErrors:Int,val errorRatePercent:Double,val latencyMs:AdminLatency,val classification:AdminClassificationPerformance,val recordedErrors:Int)
data class AuditIntegrity(val valid:Boolean,val checked:Int,val headHash:String?,val brokenAuditLogId:Int?,val reason:String?)
data class AdminBackupResponse(val status:String,val backupFile:String,val sizeBytes:Long)
data class AdminUserItem(val id:Int,val name:String,val username:String,val email:String,val role:String,val languagePreference:String?,val notificationsEnabled:Boolean?,val authProvider:String?,val createdAt:String?)
data class AdminErrorItem(val id:Int,val requestId:String?,val method:String?,val path:String?,val errorType:String?,val message:String?,val createdAt:String?)
data class BackupFileInfo(val filename:String,val sizeBytes:Long,val sizeKb:Double,val createdAt:String)
data class DatasetSampleItem(val id:Int,val smsId:Int?,val message:String,val senderNo:String?,val language:String,val expectedLabel:String?,val status:String,val reviewNote:String?,val duplicateCount:Int,val consentConfirmed:Boolean,val createdAt:String)
data class ReviewSampleRequest(val status:String,val reviewNote:String?=null)
data class CreateVersionRequest(val versionTag:String)
data class DatasetVersionItem(val id:Int,val versionTag:String,val sampleCount:Int,val filePath:String,val createdAt:String)
data class DuplicateSampleItem(val message:String,val duplicateCount:Int)
