package com.kriss.smsshield

import android.content.Intent
import android.os.Bundle
import android.util.Patterns
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import androidx.core.widget.doAfterTextChanged
import com.kriss.smsshield.api.RetrofitClient
import com.kriss.smsshield.auth.FacebookAuthHelper
import com.kriss.smsshield.auth.FirebaseAuthManager
import com.kriss.smsshield.auth.GoogleAuthHelper
import com.kriss.smsshield.databinding.ActivityLoginBinding
import com.kriss.smsshield.model.FirebaseSyncRequest
import com.kriss.smsshield.model.LoginRequest
import com.kriss.smsshield.model.TokenResponse
import com.kriss.smsshield.report.BatchHistoryStore
import com.kriss.smsshield.storage.SessionManager
import kotlinx.coroutines.launch
import org.json.JSONObject
import retrofit2.Response

/**
 * All sign-in methods (email/password, Google, Facebook) authenticate
 * against Firebase first, then exchange the resulting Firebase ID token
 * for this app's own session JWT via POST /api/auth/firebase-sync. This
 * keeps a single source of truth for "is this password/credential valid"
 * (Firebase) instead of splitting it between Firebase and this backend —
 * which is exactly what made Forgot Password unreliable before: it must
 * reset the same credential that login actually checks.
 */
@Suppress("SpellCheckingInspection")
class LoginActivity : AppCompatActivity() {
    private lateinit var b: ActivityLoginBinding
    private lateinit var googleAuthHelper: GoogleAuthHelper
    private lateinit var facebookAuthHelper: FacebookAuthHelper
    private val firebaseAuth = FirebaseAuthManager()

    private val googleSignInLauncher =
        registerForActivityResult(androidx.activity.result.contract.ActivityResultContracts.StartActivityForResult()) { result ->
            googleAuthHelper.extractIdToken(
                result.data,
                onSuccess = { googleIdToken -> completeGoogleSignIn(googleIdToken) },
                onError = { message -> showError(message) }
            )
        }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        b = ActivityLoginBinding.inflate(layoutInflater); setContentView(b.root)
        val session = SessionManager(this)
        if (session.token() != null) {
            val destination = if (session.role() == "admin") AdminActivity::class.java else HomeActivity::class.java
            startActivity(Intent(this, destination))
            finish()
            return
        }
        session.rememberedEmail()?.let {
            b.usernameInput.setText(it)
            b.rememberPasswordCheckBox.isChecked = true
        }

        // Generated by the Google Services Gradle plugin from google-services.json.
        // This is the Web OAuth client ID used as the ID-token audience.
        googleAuthHelper = GoogleAuthHelper(this, getString(R.string.google_web_client_id))
        facebookAuthHelper = FacebookAuthHelper(this)
        b.usernameInput.doAfterTextChanged { b.usernameInputLayout.error = null; b.errorText.text = "" }
        b.passwordInput.doAfterTextChanged { b.passwordInputLayout.error = null; b.errorText.text = "" }

        b.registerButton.setOnClickListener { startActivity(Intent(this, RegisterActivity::class.java)) }
        b.loginButton.setOnClickListener { login() }
        b.forgotPasswordButton.setOnClickListener { startActivity(Intent(this, ForgotPasswordActivity::class.java)) }
        b.googleSignInButton.setOnClickListener { googleSignInLauncher.launch(googleAuthHelper.signInIntent()) }
        b.facebookSignInButton.setOnClickListener {
            facebookAuthHelper.login(
                onSuccess = { facebookAccessToken -> completeFacebookSignIn(facebookAccessToken) },
                onCancel = { showError(getString(R.string.social_login_cancelled)) },
                onError = { message -> showError(message) }
            )
        }
    }

    @Suppress("OVERRIDE_DEPRECATION")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        facebookAuthHelper.callbackManager.onActivityResult(requestCode, resultCode, data)
    }

    private fun showError(message: String) {
        b.errorText.text = message.ifBlank { getString(R.string.social_login_failed) }
    }

    private fun onAuthSuccess(result: TokenResponse) {
        val remember = b.rememberPasswordCheckBox.isChecked
        val session = SessionManager(this)
        session.saveToken(result.accessToken, persist = true)
        session.saveRole(result.user.role)
        session.saveRememberedEmail(if (remember) b.usernameInput.text?.toString()?.trim() else null)
        
        Toast.makeText(this, R.string.login_success, Toast.LENGTH_SHORT).show()

        if (result.user.role == "admin") {
            startActivity(Intent(this, AdminActivity::class.java))
        } else {
            val guidePrefs = getSharedPreferences("kriss_login_guides", MODE_PRIVATE)
            val guideKey = "seen_${result.user.id}"
            val showGuide = !guidePrefs.getBoolean(guideKey, false)
            startActivity(
                Intent(this, HomeActivity::class.java)
                    .putExtra(HomeActivity.EXTRA_SHOW_FIRST_LOGIN_GUIDE, showGuide)
                    .putExtra(HomeActivity.EXTRA_GUIDE_KEY, guideKey)
            )
        }
        finish()
    }

    private suspend fun syncWithBackend() {
        val idToken = firebaseAuth.currentIdToken()
        val r: Response<TokenResponse> = RetrofitClient.api(this@LoginActivity).firebaseSync(FirebaseSyncRequest(idToken = idToken))
        if (r.isSuccessful && r.body() != null) {
            onAuthSuccess(r.body()!!)
        } else {
            showError(friendlyBackendError(r.errorBody()?.string()))
        }
    }

    private fun friendlyBackendError(body: String?): String = try {
        val detail = JSONObject(body.orEmpty()).optString("detail")
        when {
            detail.contains("already uses this email", ignoreCase = true) ->
                getString(R.string.email_account_already_exists)
            detail.isBlank() -> getString(R.string.social_login_failed)
            else -> detail
        }
    } catch (_: Exception) {
        getString(R.string.social_login_failed)
    }

    private fun completeGoogleSignIn(googleIdToken: String) {
        b.loading.visibility = View.VISIBLE
        lifecycleScope.launch {
            try {
                firebaseAuth.signInWithGoogleIdToken(googleIdToken)
                syncWithBackend()
            } catch (e: Exception) {
                showError(getString(R.string.backend_connection_error, e.localizedMessage.orEmpty()))
            } finally {
                b.loading.visibility = View.GONE
            }
        }
    }

    private fun completeFacebookSignIn(facebookAccessToken: String) {
        b.loading.visibility = View.VISIBLE
        lifecycleScope.launch {
            try {
                firebaseAuth.signInWithFacebookAccessToken(facebookAccessToken)
                syncWithBackend()
            } catch (e: Exception) {
                showError(getString(R.string.backend_connection_error, e.localizedMessage.orEmpty()))
            } finally {
                b.loading.visibility = View.GONE
            }
        }
    }

    private fun login() {
        val u = b.usernameInput.text?.toString()?.trim().orEmpty()
        val p = b.passwordInput.text?.toString().orEmpty()
        b.usernameInputLayout.error = null
        b.passwordInputLayout.error = null
        var valid = true
        if (u.isBlank()) {
            b.usernameInputLayout.error = getString(R.string.email_invalid)
            valid = false
        } else if (u.contains("@") && !Patterns.EMAIL_ADDRESS.matcher(u).matches()) {
            b.usernameInputLayout.error = getString(R.string.email_invalid)
            valid = false
        } else if (!u.contains("@") && u.length < 3) {
            b.usernameInputLayout.error = "Username must be at least 3 characters"
            valid = false
        }
        if (p.isBlank()) {
            b.passwordInputLayout.error = getString(R.string.password_required)
            valid = false
        }
        if (!valid) return
        b.loading.visibility = View.VISIBLE; b.loginButton.isEnabled = false; b.errorText.text = ""
        lifecycleScope.launch {
            try {
                val response = RetrofitClient.api(this@LoginActivity).login(LoginRequest(u, p))
                if (response.isSuccessful && response.body() != null) {
                    onAuthSuccess(response.body()!!)
                } else {
                    val errorDetail = try {
                        val errJson = JSONObject(response.errorBody()?.string().orEmpty())
                        errJson.optString("detail", getString(R.string.invalid_email_or_password))
                    } catch (_: Exception) {
                        getString(R.string.invalid_email_or_password)
                    }
                    b.usernameInputLayout.error = errorDetail
                    b.passwordInputLayout.error = errorDetail
                    b.errorText.text = errorDetail
                }
            } catch (e: Exception) {
                b.errorText.setText(R.string.connection_error)
            } finally {
                b.loading.visibility = View.GONE; b.loginButton.isEnabled = true
            }
        }
    }
}
